/**
 * Bun-side coverage ledger for SERVER-LOCAL tools — the analog of pytest's
 * `tests/harness/coverage.py`, for the tools the pytest `@covers` oracle can
 * never see.
 *
 * The bridge-operation manifest (`tests/harness/operations.py`, generated by
 * `tests/tools/regen_operations.py`) is `(server-sendable wire names ∩ C++
 * dispatch keys) ∪ {ping}` — so registry tools whose wire name (`command ??
 * name`) has NO C++ dispatch key (`catalog_*`, `code_*`, `result_read`,
 * `build_status`, composites like `actor_spawn_physics`, …) are excluded from
 * pytest coverage by construction. Their ledger lives here instead: a bun test
 * declares what it proves with
 *
 *     import { covers } from "./harness/coverage.ts";
 *
 *     covers("catalog_call");
 *     test("catalog_call dispatches + validates", ...);
 *
 * and the gate (`test/coverage.test.ts`) statically scans the test sources —
 * like the pytest guard, independent of filters / partial runs — asserting the
 * declared set equals the server-local set.
 */

import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { buildRegistry } from "../../src/register.ts";
import { PLUGIN_SRC } from "./env.ts";

/** No-op annotation: marks the following test as covering server-local tools.
 *  The authoritative collection is the static scan below. */
export function covers(..._tools: string[]): void {}

const CPP_DISPATCH = /CommandType\s*==\s*TEXT\("([a-zA-Z0-9_]+)"\)/g;
const COVERS_LITERAL = /covers\(\s*((?:"[a-zA-Z0-9_]+"\s*,?\s*)+)\)/g;
const STR = /"([a-zA-Z0-9_]+)"/g;

/** Every wire name the C++ plugin dispatches on (same regex as
 *  tests/tools/regen_operations.py — derived from source, never hand-kept). */
export function cppDispatchKeys(): Set<string> {
  const priv = join(PLUGIN_SRC, "Source", "UnrealMCP", "Private");
  const keys = new Set<string>();
  for (const f of readdirSync(priv, { recursive: true }) as string[]) {
    if (!String(f).endsWith(".cpp")) continue;
    const text = readFileSync(join(priv, String(f)), "utf-8");
    for (const m of text.matchAll(CPP_DISPATCH)) keys.add(m[1]!);
  }
  return keys;
}

/** Canonical registry tools that never hit the bridge: wire name (`command ??
 *  name`) has no C++ dispatch key. These are bun's to cover; everything else
 *  is the pytest parity oracle's job under its wire name. */
export function serverLocalTools(): string[] {
  const keys = cppDispatchKeys();
  return buildRegistry()
    .all()
    .filter((t) => !keys.has(t.command ?? t.name))
    .map((t) => t.name)
    .sort();
}

/** Statically collect every tool named in a covers(...) call under a test dir
 *  (recursive; skips the gate itself, which mentions covers() in prose). */
export function scanCoveredTools(testDir: string): Set<string> {
  const found = new Set<string>();
  for (const f of readdirSync(testDir, { recursive: true }) as string[]) {
    const rel = String(f);
    if (!rel.endsWith(".test.ts") || rel.endsWith("coverage.test.ts")) continue;
    const text = readFileSync(join(testDir, rel), "utf-8");
    for (const group of text.matchAll(COVERS_LITERAL)) {
      for (const s of group[1]!.matchAll(STR)) found.add(s[1]!);
    }
  }
  return found;
}
